package com.boatarde.regatasimulator.flows;

public enum WorkflowDataKey {
    MEME_FILE, REGATA_SIMULATOR_BOT, SEND_MESSAGE, SOURCE_FILES, TELEGRAM_UPDATE, TEMPLATE_FILE, TEMPLATE_AREAS,
    CREATING_TEMPLATE_MESSAGE
}
