package com.boatarde.regatasimulator.flows;

public enum WorkflowDataKey {
    REGATA_SIMULATOR_BOT,
    TELEGRAM_UPDATE,
    SEND_MESSAGE,
    GALLERY_DL_CURRENT_RESULT, GALLERY_DL_CURRENT_METADATA, SEND_MEDIA_GROUP, GALLERY_DL_RESULTS_ITERATOR,
    GALLERY_DL_CURRENT_RESULT_METADATA_ITERATOR, TEMPLATE_DIRECTORY, SOURCE_FILE, MEME_FILE, GALLERY_DL_RESULTS
}
