package com.boatarde.regatasimulator.flows;

public enum WorkflowAction {
    BUILD_MEME_STEP, BUILD_PONG_MESSAGE, GET_RANDOM_SOURCE, GET_RANDOM_TEMPLATE, NONE, SEND_MEME_STEP, CREATE_TEMPLATE,
    DELETE_REVIEW_TEMPLATE, CONFIRM_REVIEW_TEMPLATE, SEND_TEMPLATE_APPROVED_MESSAGE_STEP,
    SEND_TEMPLATE_REJECTED_MESSAGE, BACKUP_JSON_DB_STEP, SEND_MESSAGE_STEP, SEND_REPORT_STEP, CREATE_SOURCE
}
