server:
  forward-headers-strategy: NATIVE
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
telegram:
  creator:
    id: ENC(XTQfepj29h3jk+kwHcDfIt/lzvLcvaMpWxLme6VEodP8Rpz26t/g98sXvUC/gtah)
  bots:
    regata-simulator:
      token: ENC(dtSase99ZO5H3VM+xGZyDSfs/SXusR6aYKoWk9dNUjc29raaB/PYk4k0wftQ89L3h6bKB74wfnoLAtFF90xNraA32DiJq11aBpkZpoQU0xg=)
      username: ENC(pNyHJWQxcfDqIk2TbQwG5rig8UpbmGtp5vQNygg3FNJ1boz3eY6NkUshYV1OJFMmrI+ApaHjW3ZVLdQ6Ag0iVA==)

logging.level.org.springframework.security: DEBUG