telegram:
  creator:
    id: ENC(XTQfepj29h3jk+kwHcDfIt/lzvLcvaMpWxLme6VEodP8Rpz26t/g98sXvUC/gtah)
  bots:
    regata-simulator:
      token: ENC(czJiMJy/bO2vxQZly2IcO2hboNnfs1omPVGVtCfkrMSnpEGrV5ND1CX70P4URTAyYnb1JNAGbqPFheznaMkzrUk4cAvB+AhsHKhaZkBmGpg=)
      username: ENC(N0BtNMnwS6RMePHIGJFjZvimD+9zIlLq3ab9bq6ZDwEBkL71Yis0hDpjy52cTlq9KyLRQPuwQTrleCpsI6HlrQ==)
      channel: ENC(wkM1VOa7jfFQjlDQ12Ylor14Ys87X9Ifc0wx7C3PnDt//sVr+Mbx74Ne08/ANYtT)
      backup-chat: ENC(C7Bkhanhc1S8B3rbXkseujhRxil8nOYCpafG5zdK3O8R8ri3tOiBkRgvX50og6oG)
    bilu-tags:
      token: ENC(USgjSdg7SqUskQZqek4ugZ0gIWwBv/ShBhLrxiMQblXslCh3m8nRhjlLDQlOQGFBDUva2xQuGcrhYQ2BZDKDOXndADyAMXS7/uuJT8Qf/cI=)
