spring:
  application:
    name: bilubot
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
jasypt:
  encryptor:
    password: ${REGATA_SIMULATOR_ENC_PASSWORD}
regata-simulator:
  sources:
    path: ${REGATA_SIMULATOR_SOURCES_PATH}
  templates:
    path: ${REGATA_SIMULATOR_TEMPLATES_PATH}
magick:
  path: ${MAGICK_PATH}
web-admin:
  username: ENC(a+52ciCbjfdlGZzl1LUqul7UdgrGEu1+glWkeZ2plrlx2b1PBPk8S3LmIbcimHR4)
  password: ENC(z0G/zDkWVyOkkyjxVv14iyc3SD2Tpcbf79ap5shPDM21zHt/02ebwNbO9BjOpCgo)
