spring:
  application:
    name: bilubot
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
jasypt:
  encryptor:
    password: ${REGATA_SIMULATOR_ENC_PASSWORD}
regata-simulator:
  sources:
    path: ${REGATA_SIMULATOR_SOURCES_PATH}
  templates:
    path: ${REGATA_SIMULATOR_TEMPLATES_PATH}